#!/usr/bin/env bash
# Displays informtation about subdomains.


# Function to display information about a subdomain
display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    local destination="$4"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to process subdomains
process_subdomains() {
    local domain="$1"
    local subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print length($0) ? "A" : "CNAME"}')
        destination=$(dig +short -t A "$subdomain.$domain" | head -n 1)
        display_info "$domain" "$subdomain" "$record_type" "$destination"
    done
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 1 ]; then
    domain="$1"
    process_subdomains "$domain"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print length($0) ? "A" : "CNAME"}')
    destination=$(dig +short -t A "$subdomain.$domain" | head -n 1)
    display_info "$domain" "$subdomain" "$record_type" "$destination"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
