#!/usr/bin/env bash
# Function to get record type and destination of a domain
get_record() {
    local domain=$1
    local result=$(dig +short -t A $domain)

    if [[ -n $result ]]; then
        echo "The subdomain $domain is a A record and points to $result"
    else
        echo "The subdomain $domain does not seem to have an A record"
    fi
}

# Check if domain is provided
if [[ -z $1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1

# Check if subdomain is provided
if [[ -n $2 ]]; then
    get_record "$2.$domain"
else
    for subdomain in www lb-01 web-01 web-02; do
        get_record "$subdomain.$domain"
    done
fi
