#!/usr/bin/env bash
# Function to get record type and destination of a domain
get_record() {
    local domain=$1
    local subdomain=$2
    local result=$(dig +short -t A "$subdomain.$domain")

    if [[ -n $result ]]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    else
        echo "The subdomain $subdomain does not seem to have an A record"
    fi
}

# Check if domain is provided
if [[ -z $1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1

# Check if subdomain is provided
if [[ -n $2 ]]; then
    get_record "$domain" "$2"
else
    for subdomain in www lb-01 web-01 web-02; do
        get_record "$domain" "$subdomain"
    done
fi
