#!/usr/bin/env bash
# install load balancer

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    default_backend http_back

backend http_back
    balance roundrobin
    server 414795-web-01 54.82.82.3:80 check
    server 414795-web-02 18.209.178.150:80 check
EOF

# shellcheck disable=SC2154
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Restart HAProxy to apply the changes
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

echo "HAProxy has been installed and configured successfully."
