#!/usr/bin/env bash
# This script displays lines containing the word 'bash' and extracts the PID of the Bash process.
# shellcheck disable=SC2009
# Use ps and grep to filter lines containing the word 'bash'
ps aux | grep '[b]ash'
