#!/usr/bin/env bash
# Using a while loop to display "Best School" 10 times
# Counter variable
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((count++))
done
