#!/usr/bin/env bash
# Using a while loop to display numbers and messages based on loop iteration
# Counter variable
count=1
while [ $count -le 20 ]; do
    case $count in
        4)
            echo $count
            echo "bad luck from China"
            ;;
        9)
            echo $count
            echo "bad luck from Japan"
            ;;
        17)
            echo $count
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done
